- hosts: IP_ADDRESS
  tasks:
    - name: Docker repo
      yum_repository:
        name: docker
        description: repo for docker
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: no
- name: Installing docker
      command:
        cmd: yum install docker-ce --nobest -y
- name: install python3.6
      package:
        name: python36
        state: present
- name: Starting and enabling docker service
      service:
        name: docker
        state: started
        enabled: yes
- name: conf pip for docker
      pip:
        name: docker-py
- name: Pull httpd docker iso
      docker_image:
        name: httpd
        source: pull
- name: git
      git:
        repo: GITHUB_REPO
        clone: yes
        dest: /var/www/html
- name: docker container
      docker_container:
        name: mywebserver
        image: httpd
        exposed_ports:
          - 80
        ports:
          - 4444:80
        volumes:
          - /var/www/html/:/usr/local/apache2/htdocs/
